apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: activemq-artemis-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  - serviceaccounts
  - imagestreams
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - broker.amq.io
  resources:
  - '*'
  - activemqartemisaddresses
  - activemqartemisscaledowns
  - activemqartemis
  verbs:
  - '*'
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  - routes/custom-host
  - routes/status
  verbs:
  - get
  - list
  - watch
  - create
  - delete
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
  - create
  - delete
- apiGroups:
    - rbac.authorization.k8s.io
  resources:
    - clusterrolebindings
    - clusterroles
    - rolebindings
    - roles
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - image.openshift.io
  resources:
    - imagestreams
    - imagestreamimages
  verbs:
    - create
    - get
    - list
    - watch
- apiGroups:
    - build.openshift.io
  resources:
    - buildconfigs
  verbs:
    - create
    - get
    - list
    - watch